### ISSUE TITLE
MACRO_LUA_CALLBACK_RESULT_REF in case of OnWeaponFire is not working sometimes.

### ISSUE THREAD

**Issue by YoungFlyme** [Henningstone/HMod#24]
I made some tests, and found out that the
`MACRO_LUA_CALLBACK_RESULT_REF("OnWeaponFire", Result, m_ActiveWeaponSlot, ProjStartPos, Direction)` is not working sometimes (Seems if my weapon got too less reload it simply dont launch the lua function at all!)
What i wanna say with that is, that lua didnt even got a call on that function an ofcourse can't return anything! This is ruining the most of my current mod which modifies all weapons and pretty much need that function/event.

I made a little test with debug prints (they show me that the code, which is only getting launched when i return not true at all) gets launched, but this is impossible because i always return true at all.

In my 2nd test i just modified the default value from **false** to **true** and it worked perfectly (it always printed my debug print in this function :+1: ). Ofc. it do not work at all if i delete my custom function and let the default value at **true**. This says to me that lua/the callback event must return nil at all. 

Based on the fact that this phenomenon only occurs when i call this event in a short period of time i suppose it have to be something with a thread (or lua at all?).

Please take a look onto this.

**Comment by Henningstone** [comment]
Issue cause:

the lua event recursion prevention only checks if the call came from lua, but not if it actually came from the method that's calling the event. Thus, a call from lua will currently *never* trigger an event.
