### ISSUE TITLE
Port will only use the standart port, not the port in the config file.

### ISSUE THREAD

**Issue by YoungFlyme** [Henningstone/HMod#26]
You should take a look on that one.

**Comment by YoungFlyme** [comment]
Well, i got this in an older version the newer semms to work fine. Maybe you check the out or just close the issue!

**Comment by Henningstone** [comment]
Works as intended. Just make sure the config file is actually getting executed (for autoexec.cfg the server must be run with working directory set to autoexec.cfg's path).
