### ISSUE TITLE
Per-Player rcon and custom auth levels

### ISSUE THREAD

**Issue by YoungFlyme** [Henningstone/HMod#4]
I currently code a mod via lua and need much output. The chat is not optimal for that but a console.
The only console we can use on a server is the rcon. So I need a _fake-auth_ in the rcon to give a player only player-related commands. (Player related voting menu is not exactly what i want).
You can compare this almsost with the ddnet rcon expect that every tee should gain a own _fake-auth_ indeed of a auth-level. So we can write to each tee's rcon without a interference of the other rcon's.

You should just allow us a special auth-feature and 1 hardcoded command
`login s` to login as admin.
The other commands should be coded by lua and all tees must gain their own rcon via lua!

Hope this will came true! We will rise to a new era in Teeworlds with that :3

**Comment by Henningstone** [comment]
Seperated rcon for every player is planned nevertheless as a courtesy feature (why the heck isn't that in vanilla already?!), and gametypes should be able to create custom auth levels as well as manage access to commands to fit their needs (e.g. city mods seem to need way more auth levels than, say, fng).
I think that should be sufficient tools to realize whatever you want to do there.

> Hope this will came true! We will rise to a new era in Teeworlds with that :3

åh nej, cmon plx stay reel.
